export const INCREMENT_COUNTER = "INCREMENT_COUNTER"

export const ADD_FACILITY = "ADD_FACILITY"

export const DELETE_DATA = "DELETE_DATA"

export const UPDATE_DATA = "UPDATE_DATA"

export const GET_DATA = "GET_DATA"

export const LOADING_FACILITY = "LOADING_FACILITY"


export const ADD_PRODUCTS = "ADD_PRODUCTS"

export const DELETE_PRODUCTS = "DELETE_PRODUCTS"

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"

export const GET_PRODUCTS = "GET_PRODUCTS"

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';




export const GET_FRUTES_DATA ="GET_FRUTES_DATA"


export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ERROR_CATEGORY = 'ERROR_CATEGORY';




export const LOADING_SUBCATEGORY = 'LOADING_SUBCATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const ERROR_SUBCATEGORY = 'ERROR_SUBCATEGORY';